name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      run:
        description: ""
        required: true
        default: run
        type: choice
        options:
          - run


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle
      - name: Clone Getter
        run: |
          cd Getter
          git submodule init
          git submodule update
      - name: Clone Getter
        run: |
          ls
          cd Getter
          ls
      - name: Build with Gradle
        run: ./gradlew build
