name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      run:
        description: ""
        required: true
        default: run
        type: choice
        options:
          - run


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle

      - name: Build with Gradle
        run: |
          ./gradlew assembleRelease
          ./gradlew assembleDebug
   

      - name: Build with Gradle
        run: |
          bash ./gradlew assembleRelease
          bash ./gradlew assembleDebug
          bash ./gradlew bundleRelease

      - name: Sign Release APK
        if: success()
        id: sign_release
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: ./app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: xiao_wine
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Sign Debug APK
        if: success()
        id: sign_debug
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: ../app/build/outputs/apk/debug
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: xiao_wine
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Sign Release AAB
        if: success()
        id: sign_release_aab
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: ./app/build/outputs/bundle/release/
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: xiao_wine
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: StatusBarLyric_release
          path: ${{ steps.sign_release.outputs.signedFile }}

      - name: Upload Release AAB APK
        uses: actions/upload-artifact@v2
        with:
          name: Lyric Getter aab
          path: ${{ steps.sign_release_aab.outputs.signedFile }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: Lyric Getter debug
          path: ${{ steps.sign_debug.outputs.signedFile }}


#      - name: Post to channel
#        if: contains(github.event.head_commit.message, '[skip post]') == false
#        env:
#          CHANNEL_ID: ${{ secrets.CHANNEL_DEV_ID }}
#          BOT_TOKEN: ${{ secrets.BOT_DEV_TOKEN }}
#          RELEASE: ${{ steps.sign_release.outputs.signedReleaseFile }}
#          DEBUG: ${{ steps.sign_debug.outputs.signedReleaseFile }}
#          MAPPING: ./app/build/outputs/mapping/release/mapping.txt
#          COMMIT_MESSAGE: |+
#            Github CI
#            ```
#            ${{ github.event.head_commit.message }}
#            ```
#        run: |
#  ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
#  curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fdebug%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D" -F release="@$RELEASE" -F debug="@$DEBUG"ment%22%2C%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%22media%22%3A%22attach%3A%2F%2Fdebug%22%7D%2C%7B%22type%22%3A%22document%22%2C%22media%22%3A%22attach%3A%2F%2Fmapping%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D" -F release="@$RELEASE" -F debug="@$DEBUG" -F mapping="@$MAPPING"
